sudo: required
language: minimal
services:
- docker
script:
- make -j 5
- make -w -C test
deploy:
  skip_cleanup: true
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
env:
  global:
  - secure: LrjwEN66T79PBcO/utVY/LXFXeM0ChpZUjd2igVQHwEp4KPU6Fy+x37q/i/8d4vXOwwDIGMDT8LZDJBAsYihygLrvoL7X1wNIHcI30dYXZYfr0UCSWQthoPgXyMTW/iXrj8RCHm6oE0nJEpPquf95seteo+io5KuMUimOD2ITZrfu1PW8/9dy1mD+I8O+qyDr7+XRFBqwUcCFLO1Wk2S+wAmgq01aRJDmCtGyKZ/Wo1DhohfwooA/kgNp8Ds/e47t9ZZmwyHeGaE/VkvqYuGcjGc/E96pzWa8uNdjG184+zXtAkZBhAyfrcLW9iQvYvv62J/od2+FiHu5Bc6iwn2do1S0zsdgcxwRn5oW/bn1upBDU34sgaaGFREUiL4qK/QeXyAky90pI0FygF78E9V+KsiyrcBlWbh+exjdmcQmcaVsVp4XLBheZMkoBImdIbf8f3R8VcnvMBytO9y08GJlF4HySNep/2tUbnQIyD1vl3QjM3E03FP6W31rHuuBJj09t2NjUoXgFP9QyELvj3IhpP95QJYSEY7dXuzzUgsVNnkuIYxkEAxU8FlryugV0URlDnPGv1m/EVPXqC53Ev1oiPoPuVYbB5hVzydWIMdhNSRF7SC13V3eDSapDMLRd5rqhrnL0Q1Jk70x9CdmPgU6qnjfBW3R+dQcLsbjCF3qP4=
  - secure: pciNUH3T4fXUqZ7ksKd5Qxsog+zqAfaoDbXGas+sjhMkqMcWL4Q4NUDKL1cali9vCz6UIh9sR9YKKEBinIpp5BnuVteLfIxmhXkvpMJRJpkBGur/Cbm19qH3RPe6jbLHEXjKpJGVTo+FEQMqXWxnelq2qabBmnwppunqIhIap4B2f7ZviXuyYFFS+1L31mMGUwW7cm18yE7Lz0jmdDwfaDg84ADKEFxBTVBiZAxdUofe0Mjm+2uIvLCwjhAuPLvWPY2ugDTJk0L9roD6FC84yUZW9LX/O0xjBBBoCpFtjv1nLWBrukUs06wtVV5YvO986nmfb++A1wTBHU7r49Sm4vBjFwWa3OKuBvaK+FrwFOnigibqY3W7aqt18MdYPO3XWPQpwoVsCSY9NqLE9KyB8aUL3tUYenBeyJF4tfouej9VkaIOyKVFaYP8D4HtWCch5PWj0OWI19PctQPUTeTOO8PI1FIeGd/dwx1EQ47Vqz01H7KoCdJRu8xUh91+mFI3g41nTUoMU53ngiZ6UwWbKrCJ4AgkmlVTbtHqC0ijK3d/VpnjygomMmvewCh7lnuEjXMIPbyJahRoqUEdqGq4Nfdt0vNBO5oA9vgA9sxSw3ht7ZuvyXfkZZ4O+FTmPkoyqxMsYHeVQTKpszRfe7T8toRzMNfMgh8yg4oZkdFFH+0=
